In [ ]:
#import statements

In [1]:
import numpy as np

In [2]:
# 1-a) Create an 1-d array named 'arr_int' of integers from 45 to 55 inclusive
# 1-b) Read back first 4 elements of 'arr_int'
# 1-c) Read back last element of 'arr_int'

In [3]:
arr_int = np.arange(45,56)

In [18]:
arr_int[0:4]

array([ 0.09402896,  0.60930013,  1.57930516, -0.48236905])

In [19]:
arr_int[-1]

-0.4580229998698774

In [6]:
# 2-a) Create a 1-d array named 'arr_1' of 12 values from the random-normal distribution
# 2-b) Create a boolean array named ' arr_1_bool' which has "True" where the value in 'arr_1' is greater than 0.5
# 2-c) Reshape the 1-d array 'arr_1' to a 3 row, 4 column 2-d array called 'arr_2'

In [8]:
arr_1 = np.random.randn(12)

In [10]:
arr_1

array([ 0.09402896,  0.60930013,  1.57930516, -0.48236905,  0.64517634,
       -1.47754309, -1.24724955, -1.45001783,  1.09305226,  0.87677125,
       -1.03315456, -0.458023  ])

In [9]:
arr_1_bool = arr_1 > 0.5

In [12]:
arr_1_bool

array([False,  True,  True, False,  True, False, False, False,  True,
        True, False, False])

In [14]:
arr_2 = arr_1.reshape(3,4)

In [15]:
arr_2

array([[ 0.09402896,  0.60930013,  1.57930516, -0.48236905],
       [ 0.64517634, -1.47754309, -1.24724955, -1.45001783],
       [ 1.09305226,  0.87677125, -1.03315456, -0.458023  ]])

In [ ]:
# 3-a) Add first 4 elements of 'arr_int' to first row of 'arr_2'. Store the result as 'arr_3'
# 3-b) Find the mean of 'arr_3'

In [20]:
arr_3 = arr_int[:4] + arr_2[1]

In [21]:
arr_3.mean()

-0.43234223106927766