In [2]:
import numpy as np

# Creating Numpy Arrays

arrays from lists (np.array)

In [3]:
list_1d = [5,3,8]

In [4]:
np.array(list_1d)

array([5, 3, 8])

In [5]:
list_2d = [[3,7,18],[6,3,1]]

In [6]:
np.array(list_2d)

array([[ 3,  7, 18],
       [ 6,  3,  1]])

arrays from ranges (np.arange)

In [7]:
np.arange(3,10)

array([3, 4, 5, 6, 7, 8, 9])

In [8]:
np.arange(3,38,2.5)

array([ 3. ,  5.5,  8. , 10.5, 13. , 15.5, 18. , 20.5, 23. , 25.5, 28. ,
       30.5, 33. , 35.5])

arrays from ranges (np.linspace)

In [10]:
np.linspace(0,1,9)

array([0.   , 0.125, 0.25 , 0.375, 0.5  , 0.625, 0.75 , 0.875, 1.   ])

In [18]:
np.linspace((1,0),(10,9),10)

array([[ 1.,  0.],
       [ 2.,  1.],
       [ 3.,  2.],
       [ 4.,  3.],
       [ 5.,  4.],
       [ 6.,  5.],
       [ 7.,  6.],
       [ 8.,  7.],
       [ 9.,  8.],
       [10.,  9.]])

arrays with random valuse (np.random.randn)

In [35]:
np.random.rand(5)

array([0.23981454, 0.46546635, 0.39973389, 0.61761275, 0.11857117])

In [34]:
np.random.randn(5)

array([ 1.05861474, -0.88602032, -0.63016839,  1.33922708, -0.54670101])

In [23]:
np.random.rand(3,5)

array([[0.43852042, 0.13650097, 0.78844174, 0.59058793, 0.69542437],
       [0.41307405, 0.84075618, 0.42324987, 0.01739767, 0.43005174],
       [0.0682905 , 0.8564977 , 0.76812205, 0.9390252 , 0.04771192]])

In [33]:
np.random.randn(3,5)

array([[-0.40471028,  2.43718018, -0.84214609, -1.94038892, -1.19518574],
       [-1.04436437,  0.04491387,  0.52800654,  0.58477567, -2.20479292],
       [ 0.15631502, -1.99878515, -0.21035089, -0.55413127, -2.21679822]])

standard arrays (zeros, ones, identity matrix)

In [36]:
np.zeros(3)

array([0., 0., 0.])

In [40]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [39]:
np.ones(3)

array([1., 1., 1.])

In [42]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [43]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

Reshape Arrays

In [44]:
my_array = np.random.randn(12)

In [45]:
my_array

array([-0.31915962, -0.82718171, -0.04166803, -1.18786117,  0.30210124,
       -1.5962689 ,  0.76168378, -0.4539279 ,  0.70607508, -1.83574581,
        0.53394357,  1.69773039])

In [47]:
my_array.shape

(12,)

In [49]:
my_array.reshape(3,4)

array([[-0.31915962, -0.82718171, -0.04166803, -1.18786117],
       [ 0.30210124, -1.5962689 ,  0.76168378, -0.4539279 ],
       [ 0.70607508, -1.83574581,  0.53394357,  1.69773039]])