# Operate on Numpy Arrays

In [1]:
import numpy as np

numerical operations with **scalars** (add, substract, multiply, divide)

In [4]:
array = np.arange(3,15)

In [5]:
array

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [6]:
array + 5

array([ 8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [9]:
array - 3

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [10]:
array / 5

array([0.6, 0.8, 1. , 1.2, 1.4, 1.6, 1.8, 2. , 2.2, 2.4, 2.6, 2.8])

In [11]:
array * 6

array([18, 24, 30, 36, 42, 48, 54, 60, 66, 72, 78, 84])

In [14]:
array ** (1/2)

array([1.73205081, 2.        , 2.23606798, 2.44948974, 2.64575131,
       2.82842712, 3.        , 3.16227766, 3.31662479, 3.46410162,
       3.60555128, 3.74165739])

In [15]:
array ** 2

array([  9,  16,  25,  36,  49,  64,  81, 100, 121, 144, 169, 196])

numerical operations with **arrays** (add, substract, multiply, divide)

In [20]:
array_2 = np.arange(5,17)

In [21]:
array_2

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [22]:
array

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [23]:
array + array_2

array([ 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30])

In [24]:
array - array_2

array([-2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2])

In [25]:
array * array_2

array([ 15,  24,  35,  48,  63,  80,  99, 120, 143, 168, 195, 224])

In [26]:
array / array_2

array([0.6       , 0.66666667, 0.71428571, 0.75      , 0.77777778,
       0.8       , 0.81818182, 0.83333333, 0.84615385, 0.85714286,
       0.86666667, 0.875     ])

operation functions (dot product, transform, sum, mean, median, standard deviation, sort)

In [28]:
array_2d = np.array([[2,6,4],[7,5,3],[1,8,9]])

In [29]:
array_2d

array([[2, 6, 4],
       [7, 5, 3],
       [1, 8, 9]])

In [30]:
array_2d.dot(array_2d)

array([[ 50,  74,  62],
       [ 52,  91,  70],
       [ 67, 118, 109]])

In [31]:
array_2d.T

array([[2, 7, 1],
       [6, 5, 8],
       [4, 3, 9]])

In [32]:
array_2d.sum()

45

In [33]:
array_2d.sum(axis=0)

array([10, 19, 16])

In [35]:
array_2d.sum(axis=1)

array([12, 15, 18])

In [38]:
array_2d.mean()

array([4., 5., 6.])

In [39]:
array_2d.mean(axis=1)

array([4., 5., 6.])

In [40]:
array_2d.std()

2.581988897471611

universal functions {UFUNCs} (mod, sin, cos, greater, less, logical_and, logical_or)

In [41]:
array_2d = np.array([[2,6,4],[7,5,3],[1,8,9]])

In [42]:
array_2d

array([[2, 6, 4],
       [7, 5, 3],
       [1, 8, 9]])

In [43]:
np.mod(array_2d, 4)

array([[2, 2, 0],
       [3, 1, 3],
       [1, 0, 1]])

In [44]:
np.sin(array_2d)

array([[ 0.90929743, -0.2794155 , -0.7568025 ],
       [ 0.6569866 , -0.95892427,  0.14112001],
       [ 0.84147098,  0.98935825,  0.41211849]])

In [45]:
np.cos(array_2d)

array([[-0.41614684,  0.96017029, -0.65364362],
       [ 0.75390225,  0.28366219, -0.9899925 ],
       [ 0.54030231, -0.14550003, -0.91113026]])

In [46]:
np.greater(array_2d, 8)

array([[False, False, False],
       [False, False, False],
       [False, False,  True]])

In [49]:
np.less(array_2d, 3)

array([[ True, False, False],
       [False, False, False],
       [ True, False, False]])

In [50]:
np.logical_or(np.greater(array_2d, 8), np.less(array_2d,3))

array([[ True, False, False],
       [False, False, False],
       [ True, False,  True]])

In [51]:
np.logical_or(array_2d > 8, array_2d < 3)

array([[ True, False, False],
       [False, False, False],
       [ True, False,  True]])

In [52]:
np.logical_and(array_2d > 3, array_2d < 8)

array([[False,  True,  True],
       [ True,  True, False],
       [False, False, False]])

In [53]:
array_2d

array([[2, 6, 4],
       [7, 5, 3],
       [1, 8, 9]])

[https://numpy.org/doc/stable/reference/ufuncs.html#available-ufuncs](https://numpy.org/doc/stable/reference/ufuncs.html#available-ufuncs)