# reading from arrays

reading from 1-d arrays using index values

In [2]:
import numpy as np

In [4]:
my_array = np.arange(3,9)

In [5]:
my_array

array([3, 4, 5, 6, 7, 8])

In [6]:
my_array[2]

5

In [7]:
my_array[2:4]

array([5, 6])

In [8]:
my_array[:5]

array([3, 4, 5, 6, 7])

In [9]:
my_array[2:]

array([5, 6, 7, 8])

In [11]:
my_array[-4]

5

In [12]:
my_array[:-3]

array([3, 4, 5])

Creating a **Slice** vs a **Copy** of arrays

In [13]:
slice_my_array = my_array[1:3]

In [14]:
slice_my_array

array([4, 5])

In [15]:
slice_my_array[:] = 25

In [16]:
slice_my_array

array([25, 25])

In [17]:
my_array

array([ 3, 25, 25,  6,  7,  8])

In [25]:
copy_my_array = my_array.copy()

In [26]:
copy_my_array

array([ 3, 25, 25,  6,  7,  8])

In [27]:
copy_my_array[1] = 10

In [28]:
copy_my_array

array([ 3, 10, 25,  6,  7,  8])

In [29]:
my_array

array([ 3, 25, 25,  6,  7,  8])

reading form 2-d arrays using **index values**

In [32]:
my_2d_array = np.array([[2,3,4],[5,7,9],[11,22,33]])

In [33]:
my_2d_array

array([[ 2,  3,  4],
       [ 5,  7,  9],
       [11, 22, 33]])

In [34]:
my_2d_array[1]

array([5, 7, 9])

In [35]:
my_2d_array[1][2]

9

In [36]:
my_2d_array[1,2]

9

In [37]:
my_2d_array[:,2]

array([ 4,  9, 33])

In [38]:
my_2d_array[:2,:2]

array([[2, 3],
       [5, 7]])

reading form 1-d arrays using **conditional values**

In [39]:
rand_array = np.random.randn(10)

In [40]:
rand_array

array([-0.8455684 , -2.93812832, -2.28816608, -0.90475614, -0.04683048,
        1.08220552,  1.13084226, -1.07828846,  0.6166009 , -0.46648784])

In [42]:
bool_array = rand_array > 0

In [43]:
bool_array

array([False, False, False, False, False,  True,  True, False,  True,
       False])

In [46]:
rand_array[bool_array == True]

array([1.08220552, 1.13084226, 0.6166009 ])

In [47]:
rand_array[rand_array > 0]

array([1.08220552, 1.13084226, 0.6166009 ])

reading from 2-d arrays using **conditionals**

In [51]:
rand_2d_array = np.random.randn(15).reshape(3,5)

In [52]:
rand_2d_array

array([[-0.84910513,  1.77255888,  1.50155792,  0.85151094,  1.51758252],
       [-1.11800144, -0.50702123, -0.33303623, -0.68097104,  0.63141839],
       [-1.46325295,  1.32164847, -0.42825608, -1.31453641, -1.13515136]])

In [54]:
bool_2d_array = rand_2d_array > 0

In [55]:
bool_2d_array

array([[False,  True,  True,  True,  True],
       [False, False, False, False,  True],
       [False,  True, False, False, False]])

In [56]:
rand_2d_array[bool_2d_array]

array([1.77255888, 1.50155792, 0.85151094, 1.51758252, 0.63141839,
       1.32164847])

In [57]:
bool_2d_array[:,1]

array([ True, False,  True])

In [67]:
rand_2d_array[bool_2d_array[:,1]]

array([[-0.84910513,  1.77255888,  1.50155792,  0.85151094,  1.51758252],
       [-1.46325295,  1.32164847, -0.42825608, -1.31453641, -1.13515136]])

In [69]:
bool_2d_array[1,:]

array([False, False, False, False,  True])

In [61]:
rand_2d_array[:,bool_2d_array[1,:]]

array([[ 1.51758252],
       [ 0.63141839],
       [-1.13515136]])